### ISSUE TITLE
Error when run "ct.tl.communication_deg_detection"

### ISSUE THREAD

**Issue by chen-zhan** [zcang/COMMOT#11]
Hi, Thank you for such a great tool. I meet error when I run
` df_deg, df_yhat = ct.tl.communication_deg_detection(adata_dis500,
...     database_name = 'cellchat', pathway_name='SPP1', summary = 'receiver')`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/commot/tools/_downstream_analysis.py", line 154, in communication_deg_detection
    ro.r(string_fitGAM)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 126, in __call__
    res = conversion.rpy2py(res)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/functools.py", line 874, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/anndata2ri/r2py.py", line 28, in rpy2py_s4
    return rpy2py_single_cell_experiment(obj)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/anndata2ri/r2py.py", line 95, in rpy2py_single_cell_experiment
    obs = rpy2py_data_frame(col_data)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/anndata2ri/r2py.py", line 58, in rpy2py_data_frame
    columns = {k: rpy2py_vector(v) for k, v in slots["listData"].items()}
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/anndata2ri/r2py.py", line 58, in <dictcomp>
    columns = {k: rpy2py_vector(v) for k, v in slots["listData"].items()}
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/anndata2ri/r2py.py", line 49, in rpy2py_vector
    return pandas2ri.rpy2py(v)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/functools.py", line 874, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/public/home/niuxy/Software/miniconda3/envs/commot/lib/python3.8/site-packages/rpy2/robjects/conversion.py", line 200, in _rpy2py
    raise NotImplementedError(
NotImplementedError: Conversion 'rpy2py' not defined for objects of type '<class 'rpy2.robjects.methods.RS4'>'
`

Do you have any suggestions?

**Comment by zcang** [comment]
Hi, maybe setting up the package following this installation guide could help (see optional dependency): https://commot.readthedocs.io/en/latest/installation.html.
