### ISSUE TITLE
ct.tl.communication_deg_detection error:Not all gene IDs are present in the models object.

### ISSUE THREAD

**Issue by zwdylj** [zcang/COMMOT#14]
hi, thanks for the tool! I have a question for you.
when  I run 'ct.tl.communication_deg_detection' : 
'df_deg, df_yhat = ct.tl.communication_deg_detection(adata,
    database_name = 'cellchat', pathway_name='GRN', summary = 'receiver')'
some errors occurred: (i have no idea about this, looking forward to your reply!)
Traceback (most recent call last):
  File "/dellfsqd2/ST_LBI/USER/zhaowandong/projects/wochong/05.test/ccc/A8_deg.py", line 18, in <module>
    df_deg, df_yhat = ct.tl.communication_deg_detection(adata,
  File "/dellfsqd2/ST_LBI/USER/zhaowandong/Tools/anaconda3/envs/py3.8/lib/python3.8/site-packages/commot/tools/_downstream_analysis.py", line 168, in communication_deg_detection
    ro.r(string_cluster)
  File "/dellfsqd2/ST_LBI/USER/zhaowandong/Tools/anaconda3/envs/py3.8/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 501, in __call__
    res, visible = rinterface.evalr_expr_with_visible(   # type: ignore
  File "/dellfsqd2/ST_LBI/USER/zhaowandong/Tools/anaconda3/envs/py3.8/lib/python3.8/site-packages/rpy2/rinterface.py", line 183, in evalr_expr_with_visible
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in .clusterExpressionPatterns(models = models, nPoints = nPoints,  : 
  Not all gene IDs are present in the models object.

**Comment by Somnvs** [comment]
Hi, I encountered the same error. I believe we need to select the correct pathway name. 
We should choose the pathway name exclusively from the output of 
adata_dis500.uns['commot-cellchat-info']['df_ligrec']['pathway'].

I hope this information can be helpful.

**Comment by zzymanymoney** [comment]
I meet same problem ， can you slove this error？

**Comment by wangxizhi1** [comment]
Hello, I have the same problem. Have you solved it now？

**Comment by georgkastner** [comment]
For me it depends on the cellchat pathway: For example 'Ptn-Ncl' or 'Mdk-Ncl' work fine, but 'PDGF' or "GRN" cause the very same error.

**Comment by FelixWaern** [comment]
I've resolved it by adding the line:
`ro.r('assoRes <- na.omit(assoRes)') # Removes NAN entries` 
after 
`ro.r('assoRes = assoRes[assoRes[,"pvalue_1"] <= %f,]' % deg_pvalue_cutoff) # This creates NA entries. `
in the `communication_deg_detection()` function. For me that line created some strange NA genes which were not suppose to be there. Hope it helps!
