### ISSUE TITLE
I can't import commot

### ISSUE THREAD

**Issue by Miao-GG** [zcang/COMMOT#3]
Hi developer:
I successful install commot in my new conda environment,but i can't import it.
Here is my code:
>>> import commot as ct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/commot/__init__.py", line 5, in <module>
    from . import preprocessing as pp
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/commot/preprocessing/__init__.py", line 1, in <module>
    from ._infer_spatial import infer_spatial_information
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/commot/preprocessing/_infer_spatial.py", line 4, in <module>
    import scanpy as sc
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/sibcb1/chenluonanlab6/daihao/anaconda3/envs/commot/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Thanks for your attention!

**Comment by Miao-GG** [comment]
Oh! I have solved this error yet! It seems has problem with scanpy if it's installed by pip.
So i run 'conda install scanpy' to reinstall scanpy.And then I can import commot successfully.
